# To submit on Elzar:
#  snakemake --jobs 6 
#            --cluster "qsub -N gofocus 
#            -pe threads {threads} 
#            -l m_mem_free={resources.mem_mb}M 
#            -l gpu={resources.gpu} "   
import os
homedir = os.path.expanduser("~/")

(SAMPLES,) = glob_wildcards(homedir + "data/cococonet/sequences/{sample}_hiprio.tfa")

wildcard_constraints:
   sample = '\w+'

rule all:
    input:
        expand(homedir + "work/jones/{sample}_hiprio.pred", sample=SAMPLES)

rule gofocus:
	input: 
		homedir + "data/cococonet/sequences/{sample}_hiprio.tfa"
	output:
		homedir + "work/jones/{sample}_hiprio.predout"
	resources:
		gpu=1, mem_mb=5120
	threads: 4
	shell:
		homedir + "git/gofocus/gofocus/pytorch_goterm_pred.py -v {input} {output} "

rule sorted:
	input:
		homedir + "work/jones/{sample}_hiprio.predout"
	output:
		homedir + "work/jones/{sample}_hiprio.pred"
	resources:
		gpu=0 , mem_mb=2048
	threads: 1
	shell:
		"cat {input} | sort -k 1,1 -k 3,3rn > {output} "
		