#SAMPLES=[ 'GTEX-1CB4H-1526-SM-7MXU4','GTEX-1CB4H-2426-SM-7PBYR']

HOMEDIR = "/grid/gillis/home/hover"
SAMPLES, = glob_wildcards("/grid/gillis/home/hover/data/GTEx/v8/jon_bams/{sample}.Aligned.sortedByCoord.out.patched.md.bam")

rule all:
	input:
		expand("{homedir}/work/werner1.1/{sample}.readSorted.bam", sample=SAMPLES, homedir=HOMEDIR)


rule samtools1:
	input:
		"{homedir}/data/GTEx/v8/jon_bams/{sample}.Aligned.sortedByCoord.out.patched.md.bam",
	
	output:
		"{homedir}/work/werner1.1/{sample}.readSorted.bam"	
	
	resources:
		mem_mb=3072

	threads: 8
	
	log:
		"{homedir}/project/werner1/logs/{sample}.log"
	
	
	shell:
		"samtools sort -m 2G -o {output} -O bam -n -@ {threads} {input}"
		
		